name: C++ CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=DanielG0798_Movie-Ticket-Booking
            -Dsonar.sources=.  
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
