name: Build Qt Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.3'  # Set this to '6.2.0' if your project requires Qt6
        host: 'windows'
        target: 'desktop'

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1.0

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
        choco install visualstudio2022-workload-desktopbuild --yes

    - name: Configure CMake
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release

    - name: Build with MSBuild
      run: |
        msbuild build/Movie_Ticket_Booking.sln /p:Configuration=Release
